version: "3.0"
services:
  bookstore-datamanager:
    build: ./bookstore-data-manager
    volumes:
      - "./contrast_security.yaml:/etc/contrast/java/contrast_security.yaml"
      - "./target/dependency/contrast.jar:/tmp/contrast.jar"
    environment:
      - "CONTRAST__AGENT__JAVA__STANDALONE_APP_NAME=Bookstore Data Manager"
      - "CONTRAST__AGENT__CONTRAST_WORKING_DIR=/tmp/contrast"
      - "CONTRAST__AGENT__LOGGER__STDOUT=true"
      - "CONTRAST__SERVER__ENVIRONMENT=development"
      - "JAVA_TOOL_OPTIONS=-javaagent:/tmp/contrast.jar"
  bookstore-devservice:
    build: ./bookstore-devservice
    volumes:
      - "./contrast_security.yaml:/etc/contrast/java/contrast_security.yaml"
      - "./target/dependency/contrast.jar:/tmp/contrast.jar"
    environment:
      - "CONTRAST__AGENT__JAVA__STANDALONE_APP_NAME=Bookstore Devservice"
      - "CONTRAST__AGENT__CONTRAST_WORKING_DIR=/tmp/contrast"
      - "CONTRAST__AGENT__LOGGER__STDOUT=true"
      - "CONTRAST__SERVER__ENVIRONMENT=development"
      - "JAVA_TOOL_OPTIONS=-javaagent:/tmp/contrast.jar"
  bookstore-frontend:
    build: ./bookstore-frontend
    volumes:
      - "./contrast_security.yaml:/etc/contrast/java/contrast_security.yaml"
      - "./target/dependency/contrast.jar:/tmp/contrast.jar"
    environment:
      - "CONTRAST__AGENT__JAVA__STANDALONE_APP_NAME=Bookstore Front End"
      - "CONTRAST__AGENT__CONTRAST_WORKING_DIR=/tmp/contrast"
      - "CONTRAST__AGENT__LOGGER__STDOUT=true"
      - "CONTRAST__SERVER__ENVIRONMENT=development"
      - "JAVA_TOOL_OPTIONS=-Djavax.xml.accessExternalDTD=all -javaagent:/tmp/contrast.jar"
  bookstore-profanity-checker:
    build: ./bookstore-profanity-checker
    volumes:
      - "./contrast_security.yaml:/etc/contrast/java/contrast_security.yaml"
      - "./contrast.jar:/tmp/contrast.jar"  
    environment:
      - "CONTRAST__AGENT__JAVA__STANDALONE_APP_NAME=Bookstore Profanity Checker"
      - "CONTRAST__AGENT__CONTRAST_WORKING_DIR=/tmp/contrast"
      - "CONTRAST__AGENT__LOGGER__STDOUT=true"
      - "CONTRAST__SERVER__ENVIRONMENT=development"
      - "JAVA_TOOL_OPTIONS=-javaagent:/tmp/contrast.jar"
